apiVersion: v1
kind: Service
metadata:
  name: {{ include "weather-app.fullname" . }}
  labels:
    {{- include "weather-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    { { - range .Values.service.ports } }
    - name: { { .name } }
      protocol: { { .protocol } }
      port: { { .port } }
      targetPort: { { .targetPort } }
      nodePort: { { .nodePort } }
      { { - end } }
    { { - end } }
  selector:
    {{- include "weather-app.selectorLabels" . | nindent 4 }}
