spring.application.name=weatherData
weather.api.key=8A2GKB7KFNHWMGZDBQQRBL6HA
weather.api.unitGroup=metric
weather.api.contentType=json
weather.api.url=https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services

# Azure SQL Database Configuration
spring.datasource.url=jdbc:sqlserver://weatherdata-sql-server.database.windows.net:1433;database=weatherdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=sqladmin@weatherdata-sql-server
spring.datasource.password=Alexsirotin!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver